import type { IteratorMolecule } from 'sdf-parser';
import { expect, test } from 'vitest';

import { getMolfileId } from '../roundtrip/sdfParsing.ts';

const CCDC_MOLFILE = [
  'SOWFAL',
  '  --CCDC--012425    3D                              ',
  '',
  ' 16 20  0  0  0  0  0  0  0  0999 V2000',
  '   -6.5844   -3.5972   11.7591 Cs     3',
  '   -5.5735   -7.9711   15.9038 Cs     3',
  '  3  5  1',
  'M  CHG  3   1   1   2   1   6  -2',
  'M  END',
].join('\n');

const PUBCHEM_MOLFILE = [
  '42998209',
  '  -OEChem-02112506332D',
  '',
  ' 50 46  0     0  0  0  0  0  0999 V2000',
  '    4.7071   -0.7071    0.0000 Ti  0  0  0  0  0  0  0  0  0  0  0  0',
  'M  END',
].join('\n');

const WEBMOLKIT_MOLFILE = [
  '',
  'Generated by WebMolKit',
  '',
  '  5  4  0  0  1  0  0  0  0  0999 V2000',
  '   -2.8500    3.2500    0.0000 C   0  0',
  'M  END',
].join('\n');

function molecule(
  molfile: string,
  fields: Record<string, string | number> = {},
): IteratorMolecule {
  return { molfile, ...fields };
}

test('getMolfileId reads the molfile title line when no SDF tags are present', () => {
  expect(getMolfileId(molecule(CCDC_MOLFILE))).toBe('SOWFAL');
  expect(getMolfileId(molecule(PUBCHEM_MOLFILE))).toBe('42998209');
});

test('getMolfileId prefers a known ID-bearing SDF data field', () => {
  // eslint-disable-next-line camelcase -- SDF tag names from upstream IUPAC fixtures
  const withMculeId = molecule(CCDC_MOLFILE, { Mcule_ID: '9261759198' });

  expect(getMolfileId(withMculeId)).toBe('9261759198');
  expect(
    getMolfileId(molecule(WEBMOLKIT_MOLFILE, { ID: '_Elements.#003 ' })),
  ).toBe('_Elements.#003');
});

test('getMolfileId returns an empty string when no ID can be derived', () => {
  const blankTitle = [
    '',
    '  -OEChem-02112506332D',
    '',
    '  1  0  0  0  0  0  0  0  0  0999 V2000',
    '   10.2967   -1.5283    0.0000 Ar  0  0',
    'M  END',
  ].join('\n');

  expect(getMolfileId(molecule(blankTitle))).toBe('');
});
