import { defineConfig, globalIgnores } from 'eslint/config';
import ts from 'eslint-config-cheminfo-typescript';

export default defineConfig(
  globalIgnores([
    'coverage',
    'lib',
    'vendor',
    'build/out',
    // Generated by `npm run build-wasm`: the base64 WASM payload and the
    // Emscripten JS glue.
    'src/wasm/data.ts',
    'src/wasm/glue.ts',
  ]),
  ts,
  {
    // The Emscripten runtime and openchemlib expose mixed-case method
    // names like `UTF8ToString` that are not constructors.
    rules: { 'new-cap': ['error', { capIsNew: false }] },
  },
);
