name: Publish inchi-js library

on:
  push:
    tags:
      - 'inchi-js-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test -w inchi-js
      - run: npm publish -w inchi-js --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOT_TOKEN }}
